## version: '3.1'
## ejecutar
## docker compose up -d
services:
  samurai-senso:
    image: mysql
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root